# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @noRd
NULL

#' @noRd
seq_rcpp <- function(from_, to_, by_ = 1.0) {
    .Call(`_GeoSim_seq_rcpp`, from_, to_, by_)
}

#' @noRd
cokrige_cpp <- function(datacoord, index_missing, coord, model, sill, b, sillnugget, model_rotationmatrix) {
    .Call(`_GeoSim_cokrige_cpp`, datacoord, index_missing, coord, model, sill, b, sillnugget, model_rotationmatrix)
}

#' @noRd
cc_truncate_cpp <- function(y_simu, nfield, flag, nthres, thresholds) {
    .Call(`_GeoSim_cc_truncate_cpp`, y_simu, nfield, flag, nthres, thresholds)
}

cc_search_cpp <- function(datacoord, datavalue, coord, search_rotationmatrix, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb) {
    .Call(`_GeoSim_cc_search_cpp`, datacoord, datavalue, coord, search_rotationmatrix, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb)
}

#' @noRd
Gibbs_cosim_cpp <- function(datacoord, idata, ydata, nfield, flag, nthres, thresholds, model, sill, b, sillnugget, nrealiz, niterations, model_rotationmatrix, search_rotationmatrix, cc_unique, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb) {
    .Call(`_GeoSim_Gibbs_cosim_cpp`, datacoord, idata, ydata, nfield, flag, nthres, thresholds, model, sill, b, sillnugget, nrealiz, niterations, model_rotationmatrix, search_rotationmatrix, cc_unique, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb)
}

#' @noRd
cond_mooving_neigbor <- function(m1, simu, nvar, nrealiz, datacoord, cc_residuals, coord, search_rotationmatrix, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb, model, sill, b, sillnugget, model_rotationmatrix) {
    .Call(`_GeoSim_cond_mooving_neigbor`, m1, simu, nvar, nrealiz, datacoord, cc_residuals, coord, search_rotationmatrix, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb, model, sill, b, sillnugget, model_rotationmatrix)
}

#' @noRd
Gibbs_plurisim_cpp <- function(datacoord, idata, nfield, flag, nthres, thresholds, model, sill, b, sillnugget, nrealiz, niterations, model_rotationmatrix, search_rotationmatrix, cc_unique, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb) {
    .Call(`_GeoSim_Gibbs_plurisim_cpp`, datacoord, idata, nfield, flag, nthres, thresholds, model, sill, b, sillnugget, nrealiz, niterations, model_rotationmatrix, search_rotationmatrix, cc_unique, octant, ndata, nxsup, nysup, nzsup, xmnsup, ymnsup, zmnsup, xsizsup, ysizsup, zsizsup, ixsbtosr, iysbtosr, izsbtosr, nisb)
}

#' @noRd
set_seed <- function(seed) {
    invisible(.Call(`_GeoSim_set_seed`, seed))
}

#' @noRd
tbmain_cosimu_cpp <- function(coord, model, cc_sigma, A1, nvar, nlines, nrealiz, seed, all_lines, all_offset, all_r, all_phi, all_theta, valid_lines) {
    .Call(`_GeoSim_tbmain_cosimu_cpp`, coord, model, cc_sigma, A1, nvar, nlines, nrealiz, seed, all_lines, all_offset, all_r, all_phi, all_theta, valid_lines)
}

#' @noRd
tbmain_simu_cpp <- function(coord, model, cc_sigma, A1, nvar, nlines, nrealiz, seed, all_lines, all_offset, all_r, all_phi, all_theta, valid_lines) {
    .Call(`_GeoSim_tbmain_simu_cpp`, coord, model, cc_sigma, A1, nvar, nlines, nrealiz, seed, all_lines, all_offset, all_r, all_phi, all_theta, valid_lines)
}

